# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 06:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CongressMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('profile_image_path', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('party', models.CharField(blank=True, max_length=32, null=True)),
                ('constituency', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('status', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('congressman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pledge.CongressMan')),
            ],
        ),
        migrations.CreateModel(
            name='PledgeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('status1_vote', models.IntegerField(default=0)),
                ('status2_vote', models.IntegerField(default=0)),
                ('status3_vote', models.IntegerField(default=0)),
                ('status4_vote', models.IntegerField(default=0)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('pledge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pledge.Pledge')),
            ],
        ),
        migrations.CreateModel(
            name='PledgeEventPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('agreement_vote', models.IntegerField(default=0)),
                ('opposition_vote', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pledge_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pledge.PledgeEvent')),
            ],
        ),
    ]
