# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongressMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('profile_image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=512)),
                ('party', models.CharField(max_length=32)),
                ('constituency', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('status', models.IntegerField(default=0)),
                ('status_event', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('congressman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pledge.CongressMan')),
            ],
        ),
    ]
