# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='status_event',
            new_name='event_status',
        ),
    ]
