# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congressman',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='congressman',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
