# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge', '0002_auto_20170403_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congressman',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='congressman',
            name='constituency',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='congressman',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='congressman',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='congressman',
            name='party',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='congressman',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
