# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pledge', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeOrDisLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('dislike', models.BooleanField(default=False)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pledge.Pledge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pledge',
            name='like_dislike',
            field=models.ManyToManyField(through='pledge.LikeOrDisLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
