# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='hate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pledge',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
