# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 06:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge', '0005_auto_20170509_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='like_dislike',
            field=models.ManyToManyField(related_name='like_dislike', through='pledge.LikeOrDislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
