# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 07:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge', '0007_auto_20170512_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='like_dislike',
            field=models.ManyToManyField(through='pledge.LikeOrDislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
