# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge', '0009_merge_20170514_1414'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='PledgeComment',
        ),
        migrations.AlterField(
            model_name='pledge',
            name='like_dislike',
            field=models.ManyToManyField(through='pledge.LikeOrDislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
