# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 05:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pledge', '0010_auto_20170514_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='like_dislike',
            field=models.ManyToManyField(through='pledge.LikeOrDislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pledgecomment',
            name='pledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledge_comment_set', to='pledge.Pledge'),
        ),
    ]
