# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pledge', '0011_auto_20170519_1446'),
        ('pledge', '0011_auto_20170519_1644'),
    ]

    operations = [
    ]
