# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 13:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackpost',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedbackcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_comment_set', to='feedback.FeedbackPost'),
        ),
        migrations.AlterField(
            model_name='feedbackpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_post_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
